In [3]:
import pandas as pd

In [4]:
df_lio = pd.read_csv("C:/Users/jadeb/projet 3/MoveinLoc/Autre/lio_clean.csv")

In [5]:
df_open = pd.read_csv("C:/Users/jadeb/projet 3/MoveinLoc/Autre/df_OpenAgenda.csv")

In [6]:
df_jade = pd.read_csv("C:/Users/jadeb/projet 3/MoveinLoc/Autre/df_flanerbouger.csv")

C:\Users\jadeb\AppData\Local\Temp\ipykernel_38176\3767705358.py:1: DtypeWarning: Columns (0: dep) have mixed types. Specify dtype option on import or set low_memory=False.
  df_jade = pd.read_csv("C:/Users/jadeb/projet 3/MoveinLoc/Autre/df_flanerbouger.csv")

In [7]:
df = pd.concat([df_lio,df_open,df_jade],ignore_index=True)

In [8]:
df.to_csv("df.csv")

In [ ]:

themes_keywords = {

    'Fête nationale': [
        "14 juillet", "13 juillet", "feu d'artifice", "feux d'artifice",
        "retraite aux flambeaux", "fête nationale", "bal des pompiers",
        "bal populaire", "cérémonie patriotique"
    ],

    'Fête patronale': [
        "fête patronale", "fête votive", "fête locale", "ducasse",
        "fête du village", "saint", "sainte", "comice"
    ],

    'Marché de Noël': [
        'marché de noël', 'marché noël', 'noel', 'noël'
    ],

    'Marché': [
        'marché', 'marché des producteurs', 'marché producteur',
        'marché hebdomadaire', 'bio', 'producteurs', 'producteur',
        'hebdomadaire', 'legumes', 'fermier', 'artisanat', 'vente directe à la ferme',
        'braderie', 'floralies'
    ],

    'Brocante / Vide-grenier': [
        'brocante', 'vide-grenier', 'vide grenier', 'vide-greniers',
        'vide greniers', 'marché puces', 'puces',
        'bourse aux jouets', 'bourse aux vêtements'
    ],

    'Concert': [
        'concert', 'live', 'groupe', 'chorale', 'chorales',
        'fanfare', 'fanfarons', 'jazz', 'rock', 'pop',
        'dj', 'gospel', 'musique', 'musical', 'orchestre',
        'lyrique', 'bridgerton', 'bertrand belin',
        'showcase', 'tribute', 'chanson', 'chansons', 'guinguette'
    ],

    'Festival': [
        'festival', 'festi', 'festimusic', 'meeting'
    ],

    'Sport': [
        'sport', 'tournoi', 'course', 'match',
        'cyclo', 'vélo', 'velo', 'vtt',
        'trail', 'ultra trail', 'randonnée',
        'rando', 'géorando',
        'triathlon', 'tennis',
        'pétanque', 'petanque',
        'pêche', 'peche',
        'auto cross', 'cross',
        'challenge',
        'grand prix',
        'gravity race', "olympiades",
        'joutes', 'joutes nautiques', 'escalade','tour de france'
    ],
    'Visite': [
        'visite', 'visite guidée',
        'balade', 'promenade',
        'sortie nature',
        'route des',
        'nuit des églises',
        'journées du patrimoine',
        'journées européennes du patrimoine',
        'médiéval', 'médiévale', 'médiévales'
    ],
    'Exposition': [
        'exposition', 'vernissage',
        'galerie',
        'minéraux', 'mineraux',
        'fossiles',
        'patrimoine',
        'sculpture',
        'photo', 'photographie','Préhistorama'
    ],

   'Atelier': [
        'atelier',
        'initiation',
        'stage',
        'workshop',
        'sculpture',
        'aquarelle', 'dessin', 'peinture'
    ],

    'Spectacle': [
        'spectacle',
        'théâtre', 'theatre',
        'comédie',
        'projection',
        'ciné', 'cinema', 'cinéma',
        'escape game',
        'jeu de piste',
        'cirque', 'humour', 'one man show', 'stand up'
    ],

    'Enfants': [
        'enfants',
        'famille',
        'jeux',
        'jeu',
        'chasse au trésor',
        'espace jeunes',
        'lecture', 'colonie', "colo'"
    ],

    'Atelier': [
        'atelier',
        'initiation',
        'stage',
        'workshop',
        'sculpture',
        'aquarelle', 'dessin', 'peinture'
    ],

    'Foire': [
        'foire',
        'salon',
        'forum',
        'portes ouvertes'
    ],

    'Fête': [
        'fête', 'fete',
        'soirée', 'soiree',
        'bal',
        'boom',
        'halloween',
        'beaujolais',
        'after',
        'loto',
        'réunion',
        'rencontre',
        'dansant', 'dansante', 'gala', 'karaoké', 'karaoke', 'apéro', 'apero'
    ],

    'Dégustation': [
        'dégustation', 'degustation',
        'paëlla', 'paella',
        'huîtres', 'huitres',
        'boudin',
        'saucisson',
        'choucroute',
        'marron',
        
        'vente à emporter',
        'foodtruck', 'food truck', 'repas'
    ],

    'Conférence / Débat': [
        'conférence', 'conference', 'débat', 'debat', 'table ronde',
        'rencontre-débat', 'colloque'
    ],

    'Solidarité': [
        'don du sang', 'collecte de sang', 'don de sang','depistage'
    ]
}

In [9]:
from collections import defaultdict

def detecter_theme(texte):

    texte = str(texte).lower()

    scores = defaultdict(int)

    for theme, mots_cles in themes_keywords.items():

        for mot in mots_cles:

            if mot in texte:
                scores[theme] += 1

    if not scores:
        return "autre"

    meilleur_theme = max(scores, key=scores.get)

    return meilleur_theme
df['texte_complet'] = (df['nom_event'].fillna('') + ' ' + df['desc'].fillna('') + ' ' + df['keyword'].fillna('')).str.lower()
df['theme'] = df['texte_complet'].apply(detecter_theme)

In [13]:
condition = (df["theme"] == "autre")
df[condition]

,theme,nom_event,adresse,ville,cp,dep,adresse_complete,date_d,date_f,url_event,url_image,age,prix,keyword,desc,coor,Unnamed: 0.1,Unnamed: 0,texte_complet
77,autre,Retro Car Meeting,Parc de la Batellerie,Montmerle-sur-Saône,NaN,1.0,Parc de la Batellerie Montmerle-sur-Saône,2026-01-08,2026-12-31,https://france-evasion-regions.com/auvergne-rh...,NaN,NaN,NaN,NaN,Le Retro Car Meeting organise depuis 2005 à Mo...,"[46.084954, 4.758449]",NaN,NaN,retro car meeting le retro car meeting organis...
136,autre,But d'honneur,clos derrière l'église,Thoissey,NaN,1.0,clos derrière l'église Thoissey,2026-07-18,2026-07-18,https://france-evasion-regions.com/auvergne-rh...,NaN,NaN,NaN,NaN,Venez vous jouer aux boules et remporter le bu...,"[46.173022, 4.800989]",NaN,NaN,but d'honneur venez vous jouer aux boules et r...
189,autre,Concours des vétérans,Aire de loisirs,Montceaux,NaN,1.0,Aire de loisirs Montceaux,2026-09-09,2026-09-09,https://france-evasion-regions.com/auvergne-rh...,NaN,NaN,NaN,NaN,Venez nombreux participer à ce concours des vé...,"[46.12217, 0.660533]",NaN,NaN,concours des vétérans venez nombreux participe...
215,autre,Concours de belote coinchée,Salle des fêtes,Saint-Étienne-sur-Chalaronne,NaN,1.0,Salle des fêtes Saint-Étienne-sur-Chalaronne,2026-09-30,2026-09-30,https://france-evasion-regions.com/auvergne-rh...,NaN,NaN,NaN,NaN,Venez participer au concours de belote !,"[46.14987, 4.873011]",NaN,NaN,concours de belote coinchée venez participer a...
267,autre,Vente de sapins,Aire de loisirs,Montceaux,NaN,1.0,Aire de loisirs Montceaux,2026-12-05,2026-12-05,https://france-evasion-regions.com/auvergne-rh...,NaN,NaN,NaN,NaN,Le Sou des écoles de Montceaux organise sa tra...,"[46.12217, 0.660533]",NaN,NaN,vente de sapins le sou des écoles de montceaux...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57224,autre,Abbaye de royaumont,NaN,ASNIERES-SUR-OISE,95270.0,95,95270 ASNIERES-SUR-OISE,2026-12-31,2026-12-31,NaN,NaN,NaN,NaN,NaN,NaN,"[49.139257, 2.374844]",NaN,38581.0,abbaye de royaumont
57226,autre,Bourse auto moto EZANVILLE,complexe sportif de la prairie,EZANVILLE,95460.0,95,complexe sportif de la prairie 95460 EZANVILLE,2027-01-09,2027-01-09,NaN,NaN,NaN,NaN,NaN,NaN,"[43.197026, 2.339566]",NaN,38583.0,bourse auto moto ezanville
57231,autre,Caliceo cormeilles-en-parisis - vitalite,NaN,CORMEILLES-EN-PARISIS,95240.0,95,95240 CORMEILLES-EN-PARISIS,2027-03-31,2027-03-31,NaN,NaN,NaN,NaN,NaN,NaN,"[48.970343, 2.19574]",NaN,38588.0,caliceo cormeilles-en-parisis - vitalite
57235,autre,Caliceo : cormeilles-en-parisis,NaN,CORMEILLES-EN-PARISIS,95240.0,95,95240 CORMEILLES-EN-PARISIS,2027-03-31,2027-03-31,NaN,NaN,NaN,NaN,NaN,NaN,"[48.970343, 2.19574]",NaN,38592.0,caliceo : cormeilles-en-parisis
57245,autre,Peintres dans les rues,Cœur de ville,BEAUMONT-SUR-OISE,95260.0,95,Cœur de ville 95260 BEAUMONT-SUR-OISE,2027-05-16,2027-05-16,NaN,NaN,NaN,NaN,NaN,NaN,"[49.143288, 2.300596]",NaN,38602.0,peintres dans les rues

In [11]:
df.sample(20)

,theme,nom_event,adresse,ville,cp,dep,adresse_complete,date_d,date_f,url_event,url_image,age,prix,keyword,desc,coor,Unnamed: 0.1,Unnamed: 0,texte_complet
39503,Marché,Marché Hebdomadaire,place de la mairie,VARAIRE,46260.0,46,place de la mairie 46260 VARAIRE,2026-07-03,2026-07-03,NaN,NaN,NaN,NaN,NaN,NaN,"[44.357662, 1.723642]",NaN,17213.0,marché hebdomadaire
716,Sport,Randonnée groupe : L'étang de Sault (Prémilhat),"Mairie de Saint-Genest, Mairie",Saint-Genest,NaN,3.0,"Mairie de Saint-Genest, Mairie Saint-Genest",2026-08-21,2026-08-21,https://france-evasion-regions.com/auvergne-rh...,NaN,NaN,NaN,NaN,Ce parcours de randonnée est proposé par l'ass...,"[46.264309, 2.593019]",NaN,NaN,randonnée groupe : l'étang de sault (prémilhat...
32836,autre,Luiza,NaN,TOULOUSE,31500.0,31,31500 TOULOUSE,2026-11-13,2026-11-13,NaN,NaN,NaN,NaN,NaN,NaN,"[43.598457, 1.478976]",NaN,9803.0,luiza
14389,Spectacle,GUIGNOL LA TETE DANS LES ETOILES,"2 MONTÉE DU GOURGUILLON, Lyon",Lyon,NaN,69.0,"2 MONTÉE DU GOURGUILLON, Lyon Lyon",2026-07-01,2026-07-01,https://france-evasion-regions.com/auvergne-rh...,NaN,NaN,NaN,NaN,Arts & Theatre — Children's Theatre,"[45.759416, 4.82536]",NaN,NaN,guignol la tete dans les etoiles arts & theatr...
52297,Visite,Journées du Patrimoine,NaN,SAINT-MAMMES,77670.0,77,77670 SAINT-MAMMES,2026-09-19,2026-09-19,NaN,NaN,NaN,NaN,NaN,NaN,"[48.386062, 2.817849]",NaN,33199.0,journées du patrimoine
4572,Spectacle,Baludik - Le Rêve de l'aviateur,"Chemin de l'entrée de l'aérodrome, Musée Europ...",Montélimar,NaN,26.0,"Chemin de l'entrée de l'aérodrome, Musée Europ...",2026-01-01,2026-12-31,https://france-evasion-regions.com/auvergne-rh...,NaN,NaN,NaN,NaN,Découvrez le jeu de piste interactif avec le M...,"[44.581577, 4.733192]",NaN,NaN,baludik - le rêve de l'aviateur découvrez le j...
13062,Fête patronale,Marché de quartier : Saint-Esprit,Place du Marquisat,Bayonne,NaN,64.0,Place du Marquisat Bayonne,2026-07-10,2026-07-10,https://france-evasion-regions.com/nouvelle-aq...,https://cdt64.media.tourinsoft.eu/upload/12-ma...,NaN,NaN,NaN,Marché alimentaire: Tous les vendredi : fruits...,"[43.495217, -1.46727]",NaN,NaN,marché de quartier : saint-esprit marché alime...
26032,Fête nationale,Quand la cité s'embrase feu d'artifice,Ville basse Carcassonne,CARCASSONNE,11000.0,11,Ville basse Carcassonne 11000 CARCASSONNE,2026-07-14,2026-07-14,NaN,NaN,NaN,NaN,NaN,NaN,"[43.188902, 2.317261]",NaN,2410.0,quand la cité s'embrase feu d'artifice
49125,Brocante / Vide-grenier,BROCANTES COLLECTIONS ARTISANALES,Grand Port,AIX-LES-BAINS,73100.0,73,Grand Port 73100 AIX-LES-BAINS,2026-07-14,2026-07-14,NaN,NaN,NaN,NaN,NaN,NaN,"[45.70091, 5.900522]",NaN,27624.0,brocantes collections artisanales
18335,Sport,Rando 1/2 journée,15 rue de la Poste -,Servon,77170.0,NaN,15 rue de la Poste - 77170 Servon,2026-07-09,2026-07-09,NaN,https://cdn.openagenda.com/main/e24ea74183794d...,NaN,NaN,NaN,"Evry les Châteaux, le prieuré de Vernelle","[48.716073, 2.588227]",1320.0,1320.0,"rando 1/2 journée evry les châteaux, le prieur..."
23125,Enfants,Pause Poussette,97 Avenue Pierre Semard,Villiers-le-Bel,95400.0,NaN,97 Avenue Pierre Semard 95400 Villiers-le-Bel,2026-07-08,2026-08-05,NaN,https://cdn.openagenda.com/main/91eeed991bbd41...,NaN,NaN,"['Lire', 'Écouter', 'Enfants']",Le rendez-vous des tout-petits à la médiathèque.,"[49.000198, 2.41075]",6110.0,6110.0,pause poussette le rendez-vous des tout-petits...
42932,Fête patronale,Ducasse,WALLERS,WALLERS,59135.0,59,WALLERS 59135 WALLERS,2026-07-14,2026-07-14,NaN,NaN,NaN,NaN,NaN,NaN,"[50.369124, 3.393488]",NaN,20962.0,ducasse
39032,Festival,Festival mondial de la magie,NaN,NANTES,44300.0,44,44300 NANTES,2028-12-10,2028-12-10,NaN,NaN,NaN,NaN,NaN,NaN,"[47.255693, -1.528117]",NaN,16648.0,festival mondial de la magie
20125,Spectacle,Les moyens du bord,NaN,Cenon,NaN,NaN,Cenon,2026-07-17,2026-07-17,NaN,https://cdn.openagenda.com/main/0a699095464242...,NaN,NaN,NaN,Un spectacle burlesque tout public à partir de...,"[44.855288, -0.523986]",3110.0,3110.0,les moyens du bord un spectacle burlesque tout...
54828,Brocante / Vide-grenier,Vide-greniers et marché aux puces,NaN,ROBION,84440.0,84,84440 ROBION,2027-05-01,2027-05-01,NaN,NaN,NaN,NaN,NaN,NaN,"[43.856367, 5.10286]",NaN,35948.0,vide-greniers et marché aux puces
27725,autre,Manu joucla et eric massot,NaN,CAEN,14000.0,14,14000 CAEN,2026-12-15,2026-12-15,NaN,NaN,NaN,NaN,NaN,NaN,"[49.184316, -0.37193]",NaN,4186.0,manu joucla et eric massot
47387,Marché,Marché St-Germain-au-Mont-d'Or le Lundi,Place du 11 novembre 69650 Saint-Germain-au-Mo...,SAINT-GERMAIN-AU-MONT-D'OR,69650.0,69,Place du 11 novembre 69650 Saint-Germain-au-Mo...,2026-07-06,2026-07-06,NaN,NaN,NaN,NaN,NaN,NaN,"[45.884137, 4.804224]",NaN,25713.0,marché st-germain-au-mont-d'or le lundi
355,Concert,CONCERT - LES WAMPAS,Rue Gabriel Péri,Gauchy,NaN,2.0,Rue Gabriel Péri Gauchy,2026-11-14,2026-11-14,https://france-evasion-regions.com/hauts-de-fr...,NaN,NaN,NaN,NaN,Avec leur rock alternatif teinté de psychobill...,"[49.828831, 3.282357]",NaN,NaN,concert - les wampas avec leur rock alternatif...
43856,autre,Hubert felix thiefaine,NaN,LILLE,59800.0,59,59800 LILLE,2027-05-20,2027-05-20,NaN,NaN,NaN,NaN,NaN,NaN,"[50.631827, 3.091773]",NaN,21953.0,hubert felix thiefaine
55515,Fête nationale,Feu d'artifice,Limoges devant la Gare des Bénédictins,LIMOGES,87280.0,87,Limoges devant la Gare des Bénédictins 87280 L...,2026-07-13,2026-07-13,NaN,NaN,NaN,NaN,NaN,NaN,"[45.832927, 1.266967]",NaN,36820.0,feu d'artifice

In [12]:
df.to_csv("df_theme.csv")

In [12]:
print((df["theme"] == "autre").sum())

17239

In [46]:
print((df["theme"].isnull()).sum())

0

In [ ]:
#mask = (
#    (df["theme"] == "autre") &
#    (df["desc"].fillna("").str.strip() == "") &
#    (df["keyword"].fillna("").str.strip() == "")
#)

#df_artistes = df.loc[mask, ["nom_event"]].copy()

#print(len(df_artistes))

14954

In [47]:
from dotenv import load_dotenv
import os

load_dotenv()

GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")

print(GOOGLE_API_KEY[:10] + "...")

AQ.Ab8RN6I...

In [48]:
from google import genai

client = genai.Client(api_key=GOOGLE_API_KEY)

In [49]:
import re

def detecter_artistes(liste_evenements):

    texte = "\n".join(
        f"{i};{nom}"
        for i, nom in enumerate(liste_evenements)
    )

    prompt = f"""
Pour chaque ligne, réponds uniquement par :

numéro;OUI
ou
numéro;NON

Un artiste, un groupe de musique, un DJ, un chanteur, une chanteuse, un orchestre ou une chorale = OUI.

Tout le reste = NON.

Exemple :

0;OUI
1;NON
2;NON
3;OUI
"""

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )

    numeros = []

    for ligne in response.text.splitlines():

        ligne = ligne.strip()

        if re.fullmatch(r"\d+", ligne):
            numeros.append(int(ligne))

    return numeros

In [ ]:
import time

batch_size = 1000

indices = df.index.tolist()

for debut in range(0, len(indices), batch_size):

    batch = indices[debut:debut+batch_size]

    noms = df.loc[batch, "nom_event"].tolist()

    try:

        artistes = detecter_artistes(noms)

        for i in artistes:
            df.at[batch[i], "theme"] = "Concert"

        print(f"{debut+len(batch)} lignes traitées")

    except Exception as e:
        print(e)

    time.sleep(12)

1000 lignes traitées
2000 lignes traitées
3000 lignes traitées
429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 32.863174338s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '32s'}]}}
429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 20.757469092s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '20s'}]}}
429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 8.644800976s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-2.5-flash', 'location': 'global'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '8s'}]}}
429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 56.53578521s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-2.5-flash', 'location': 'global'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '56s'}]}}
429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 44.420326526s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '44s'}]}}
9000 lignes traitées
429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 16.254577108s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '16s'}]}}
429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 4.111833405s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '4s'}]}}
12000 lignes traitées
429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 34.278604487s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '34s'}]}}
429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 22.155800484s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '22s'}]}}
429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 10.042413547s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '10s'}]}}
429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 57.912832284s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-2.5-flash', 'location': 'global'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '57s'}]}}
429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 45.817985508s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-2.5-flash', 'location': 'global'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '45s'}]}}
429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 33.702207556s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '33s'}]}}
429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 21.594460824s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '21s'}]}}
429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 9.490801442s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '9s'}]}}
429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 57.271633883s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '57s'}]}}
429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 45.141917678s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '45s'}]}}
429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 32.991768489s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '32s'}]}}

In [30]:
noms = [
    "Lilly Wood and The Prick",
    "Patrick Fiori",
    "Marché Gourmand",
    "Paléolor Minéraux et Fossiles",
    "Black M"
]

print(detecter_artistes(noms))

[]

In [31]:
df["theme"].value_counts(dropna=False)

theme
Concerts              7275
NaN                   6770
concert               3754
evenement             3753
Marchés               3732
                      ...
Exposition               1
Animations de Noël       1
Grafiterias              1
Accrobranche             1
Parcs à thème            1
Name: count, Length: 96, dtype: int64

In [42]:
sorted(df["theme"].dropna().unique())

['Accrobranche',
 'Activités enfants',
 'Animations de Noël',
 'Annonces cyclistes et cyclosportives',
 'Bals Danses',
 'Bourses',
 'Brocantes',
 'Carnavals',
 'Carte',
 'Chasses au trésor',
 'Cinéma',
 'Cinémas',
 'Cirques',
 'Classique et opera',
 'Concert',
 'Concerts',
 'Concours de Belote et de Coinchée',
 'Concours de Bridges',
 'Concours de Tarots',
 'Concours de pétanque et de boules',
 'Conférences Débats',
 'Contes et lectures',
 'Coups de coeur',
 'Courses',
 'Danse',
 'Divers',
 'Evènements',
 'Evènements Country',
 'Evènements Téléthon',
 'Evènements VTT',
 'Exposition',
 'Expositions',
 'Festival',
 'Festivals',
 "Feux d'artifice",
 'Foires',
 'Food Truck commerces ambulants',
 'Fêtes',
 'Fêtes foraines',
 'Fêtes locales',
 'Fêtes médiévales',
 'Grafiterias',
 'Humour et one (wo)man show',
 'Jeux-sports',
 'Journées du patrimoine',
 'Joutes Nautiques',
 'Loisirs et tourisme',
 'Lotos Quines et Rifles',
 'Manifestation sportive',
 'Manifestations Automobiles',
 'Marché',
 'Marchés',
 'Marchés aux puces',
 'Marchés bio',
 "Marchés d'été",
 'Marchés de Noël',
 'Marchés de Producteurs',
 'Marchés de créateurs',
 'Marchés de potiers',
 'Marchés en Provence',
 'Marchés nocturnes',
 'Messes',
 'Musées',
 'Parc',
 'Parcs à thème',
 'Projection',
 'Rallyes',
 'Randonnée',
 'Randonnées, Trail ou Running',
 'Salons',
 'Soirée',
 'Sortie nature / environnement',
 'Sorties',
 'Sorties Moto',
 'Spectacle',
 'Spectacle et comedie musicale',
 'Spectacles',
 'Stages Ateliers',
 'Stages-Atelier-Jeux',
 'Théatres',
 'Tournois',
 'Vide maison',
 'Vide-greniers',
 'Visites Portes Ouvertes',
 'Visites et sorties à thèmes',
 'animation',
 'brocante',
 'concert',
 'evenement',
 'exposition',
 'festival',
 'marche',
 'nature',
 'sport',
 'tradition']

In [32]:
import time

THEMES = list(themes_keywords.keys()) + ["autre"]

def detecter_theme_llm(nom_event, desc="", keyword=""):

    prompt = f"""
Tu regardes le nom_event de toutes les lignes et s'il s'agit d'un artiste (chanteur par exemple), tu remplaces le theme actuel par Concert.

{', '.join(THEMES)}

Nom :
{nom_event}

Description :
{desc}

Mots-clés :
{keyword}

Réponds uniquement par le nom exact du thème.
"""

    for tentative in range(5):

        try:

            response = client.models.generate_content(
                model="gemini-2.5-flash",
                contents=prompt
            )

            theme = response.text.strip()

            if theme in THEMES:
                return theme

            return "autre"

        except Exception as e:

            print(f"Tentative {tentative+1} échouée : {e}")

            # attente avant de réessayer
            time.sleep(5)

    return "autre"

In [33]:
print(
    detecter_theme_llm(
        "Paléolor Minéraux et Fossiles",
        "",
        ""
    )
)

Exposition

In [34]:
mask = df["theme"] == "autre"

print(mask.sum())

0

In [18]:
idx = df[df["theme"] == "autre"].index[0]

print(df.loc[idx, ["nom_event", "theme"]])

nouveau_theme = detecter_theme_llm(
    df.at[idx, "nom_event"],
    df.at[idx, "desc"],
    df.at[idx, "keyword"]
)

print("Gemini :", nouveau_theme)

df.at[idx, "theme"] = nouveau_theme

print(df.loc[idx, ["nom_event", "theme"]])

nom_event    Retro Car Meeting
theme                    autre
Name: 77, dtype: str
Tentative 1 échouée : 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 40.084360725s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '40s'}]}}
Tentative 2 échouée : 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 34.851618723s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-2.5-flash', 'location': 'global'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '34s'}]}}
Tentative 3 échouée : 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 29.700320555s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '29s'}]}}
Tentative 4 échouée : 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 24.470016443s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-2.5-flash', 'location': 'global'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '24s'}]}}
Gemini : Exposition
nom_event    Retro Car Meeting
theme               Exposition
Name: 77, dtype: str

In [19]:
import time

mask = df["theme"] == "autre"

for idx in df[mask].index:

    theme = detecter_theme_llm(
        df.at[idx, "nom_event"],
        df.at[idx, "desc"],
        df.at[idx, "keyword"]
    )

    print(df.at[idx, "nom_event"], "->", theme)

    df.at[idx, "theme"] = theme

    time.sleep(1)  # évite de surcharger l'API

Tentative 1 échouée : 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 44.8143836s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '44s'}]}}
Tentative 2 échouée : 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 39.680845801s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '39s'}]}}
Tentative 3 échouée : 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 34.579805563s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '34s'}]}}
Tentative 4 échouée : 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 29.457124225s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '29s'}]}}
Tentative 5 échouée : 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 24.357348325s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '24s'}]}}
Colo' été 2026 - découverte de la préhistoire -> autre
Tentative 1 échouée : 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 18.14146829s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '18s'}]}}
Tentative 2 échouée : 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 13.00227739s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-2.5-flash', 'location': 'global'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '13s'}]}}
Tentative 3 échouée : 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 7.833177781s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '7s'}]}}
Tentative 4 échouée : 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 2.708893312s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '2s'}]}}
Tentative 5 échouée : 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 57.510890623s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '57s'}]}}
But d'honneur -> autre
Tentative 1 échouée : 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 50.854823757s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-2.5-flash', 'location': 'global'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '50s'}]}}
Tentative 2 échouée : 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 45.752453058s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '45s'}]}}
Tentative 3 échouée : 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 40.513717629s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-2.5-flash', 'location': 'global'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '40s'}]}}
Tentative 4 échouée : 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 35.314764681s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '35s'}]}}
Tentative 5 échouée : 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 29.844994953s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '29s'}]}}
Concours des vétérans -> autre
Tentative 1 échouée : 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 23.730563077s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '23s'}]}}
Tentative 2 échouée : 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 18.409794026s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '18s'}]}}

KeyboardInterrupt:

In [35]:
df["theme"].value_counts()

theme
Concerts              7275
concert               3754
evenement             3753
Marchés               3732
Fêtes locales         2805
                      ...
Exposition               1
Animations de Noël       1
Grafiterias              1
Accrobranche             1
Parcs à thème            1
Name: count, Length: 95, dtype: int64

In [36]:
condition = df["theme"] == "autre"
df_test = df[condition]

In [91]:
df_test.to_csv("df_test.csv")