In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import re

In [3]:
HEADERS = {"User-Agent": "Mozilla/5.0 Chrome/124.0"}

def get_parcaqua_links():
    r = requests.get("https://www.parcs-aquatiques.com/parcs-aquatiques-france/", headers=HEADERS)
    soup = BeautifulSoup(r.text, "html.parser")
    parcaqua = {}
    for li in soup.select("ul li a[href*='parcs-aquatiques.com']"):
        name = li.get_text(strip=True)
        href = li["href"]
        if name and "/carte" not in href:
            parcaqua[name] = href
    return parcaqua

In [9]:
def extract_info(url):
    r = requests.get(url, headers=HEADERS, timeout=15)
    soup = BeautifulSoup(r.text, "html.parser")

    adresse = None
    lat, lon = None, None

    # Chercher les balises <strong> qui contiennent "Adresse"
    for strong in soup.find_all("strong"):
        if "Adresse" in strong.get_text():
            # Le texte de l'adresse est dans le noeud suivant (NavigableString)
            next_node = strong.next_sibling
            if next_node:
                adresse = str(next_node).strip().lstrip(": ").strip()
            break

    # Coordonnées GPS
    gps_match = re.search(r"latitude\s*([\d.]+)\s*\|\s*longitude\s*([\d.]+)", soup.get_text())
    if gps_match:
        lat = float(gps_match.group(1))
        lon = float(gps_match.group(2))

    return {"adresse": adresse, "latitude": lat, "longitude": lon}

parc_aquatique = get_parcaqua_links()
records = []
for name, url in parc_aquatique.items():
    print(f"→ {name}")
    info = extract_info(url)
    records.append({"nom": name, "url": url, **info})
    time.sleep(0.8)

df = pd.DataFrame(records)
df.to_csv("parc_aquatique.csv", index=False, encoding="utf-8-sig")
print(df[["nom", "adresse", "latitude", "longitude"]])

→ Accueil
→ Promos
→ Carte France
→ Aqualand
→ Agen
→ Bassin d’Arcachon
→ Cap d’Agde
→ Fréjus
→ Port Leucate
→ Saint Cyprien
→ Saint Cyr sur Mer
→ Sainte Maxime
→ Aquasplash
→ Aquascope
→ Aquaboulevard
→ Aqua Béarnà Oloron Sainte Marie
→ Aquaboulevardà Paris
→ Aqua’Fun Park – Cobac Parcà Lanhélin
→ Aquajetà Narbonne Plage
→ Aqualand Agen– Walygator Sud Ouest
→ Aqualand Bassin d’Arcachon
→ Aqualand Fréjus
→ Aqualand Le Cap d’Agde
→ Aqualand Port Leucate
→ Aqualand Saint Cyprien
→ Aqualand Saint Cyr sur Mer
→ Aqualand Sainte Maxime
→ Aquaparc Isisà Dole
→ Aquascope Futuroscope
→ Aquasplashà Antibes
→ Aquatic Landesà Labenne-Océan
→ Atlantic Parkà Seignosse Océan
→ Atlantic Tobogganà Saint-Hilaire-de-Riez
→ Espace Grand Bleuà La Grande Motte
→ Iléosur l’île d’Oléron
→ Ludolacà Vesoul
→ Nyonsoleïadoà Nyons
→ O’Gliss Parken Vendée
→ Parc de la Bouscarasseà Serviers-et-Labaume
→ Pirates WorldCap d’Agde
→ Quercylandà Souillac
→ Vitam à Neydens
→ Wave Islandà Monteux
→ Western Parkà Biguglia
→ • Aquascope Futuroscope
→ • Aquaboulevard Paris
→ • Plopsaqua
                                            nom  \
0                                       Accueil
1                                        Promos
2                                  Carte France
3                                      Aqualand
4                                          Agen
5                             Bassin d’Arcachon
6                                    Cap d’Agde
7                                        Fréjus
8                                  Port Leucate
9                                 Saint Cyprien
10                            Saint Cyr sur Mer
11                                Sainte Maxime
12                                   Aquasplash
13                                    Aquascope
14                                Aquaboulevard
15              Aqua Béarnà Oloron Sainte Marie
16                         Aquaboulevardà Paris
17         Aqua’Fun Park – Cobac Parcà Lanhélin
18                      Aquajetà Narbonne Plage
19           Aqualand Agen– Walygator Sud Ouest
20                   Aqualand Bassin d’Arcachon
21                              Aqualand Fréjus
22                       Aqualand Le Cap d’Agde
23                        Aqualand Port Leucate
24                       Aqualand Saint Cyprien
25                   Aqualand Saint Cyr sur Mer
26                       Aqualand Sainte Maxime
27                          Aquaparc Isisà Dole
28                        Aquascope Futuroscope
29                          Aquasplashà Antibes
30                Aquatic Landesà Labenne-Océan
31               Atlantic Parkà Seignosse Océan
32     Atlantic Tobogganà Saint-Hilaire-de-Riez
33           Espace Grand Bleuà La Grande Motte
34                       Iléosur l’île d’Oléron
35                              Ludolacà Vesoul
36                          Nyonsoleïadoà Nyons
37                        O’Gliss Parken Vendée
38  Parc de la Bouscarasseà Serviers-et-Labaume
39                      Pirates WorldCap d’Agde
40                         Quercylandà Souillac
41                              Vitam à Neydens
42                         Wave Islandà Monteux
43                       Western Parkà Biguglia
44                      • Aquascope Futuroscope
45                        • Aquaboulevard Paris
46                                  • Plopsaqua

                                             adresse   latitude  longitude
0                                                NaN        NaN        NaN
1                                                NaN        NaN        NaN
2                                                NaN        NaN        NaN
3                                                NaN        NaN        NaN
4                Château de Caudouin 47310 Roquefort  44.186173   0.579221
5                 route des lacs 33470 Gujan-Mestras        NaN        NaN
6   2 avenue des Iles d’Amérique 34300 Le Cap d’Agde  43.280843   3.494517
7                Quartier le Capou D559 83600 Fréjus  43.419434   6.728501
8            avenue du Roussillon 11370 Port Leucate  42.842203   3.042208
9   avenue des Champs de Neptune 66750 Saint Cyprien  42.601210   3.032193
10          ZAC des Pradeaux 83270 Saint-Cyr-sur-Mer  43.184257   5.692833
11        Avenue Gaston Rebuffat 83120 Sainte Maxime  43.327553   6.619147
12                   306 avenue Mozart 06600 Antibes  43.614914   7.120413
13    Avenue René Monory 86360 Chasseneuil-du-Poitou  46.663320   0.361748
14                  4-6 rue Louis Armand 75015 Paris  48.833049   2.277545
15                       Le Faget de Goès 64400 Goès        NaN        NaN
16                  4-6 rue Louis Armand 75015 Paris  48.833049   2.277545
17                          route D75 35620 Lanhélin        NaN        NaN
18            route de Gruissan 11100 Narbonne Plage  43.147748   3.153190
19               Château de Caudouin 47310 Roquefort  44.186173   0.579221
20                route des lacs 33470 Gujan-Mestras        NaN        NaN
21               Quartier le Capou D559 83600 Fréjus  43.419434   6.728501
22  2 avenue des Iles d’Amérique 34300 Le Cap d’Agde  43.280843   3.494517
23           avenue du Roussillon 11370 Port Leucate  42.842203   3.042208
24  avenue des Champs de Neptune 66750 Saint Cyprien  42.601210   3.032193
25          ZAC des Pradeaux 83270 Saint-Cyr-sur-Mer  43.184257   5.692833
26        Avenue Gaston Rebuffat 83120 Sainte Maxime  43.327553   6.619147
27                 Allée des Prés Buffard 39100 Dole  47.073275   5.486750
28    Avenue René Monory 86360 Chasseneuil-du-Poitou  46.663320   0.361748
29                   306 avenue Mozart 06600 Antibes  43.614914   7.120413
30             route de la Plage 40530 Labenne-Océan        NaN        NaN
31       2 avenue de la Grande Plage 40510 Seignosse        NaN        NaN
32    42 Avenue des Becs 85270 Saint-Hilaire-de-Riez  46.764210   2.031610
33         195 rue Saint-Louis 34280 La Grande Motte  43.562553   4.098635
34         Iléo, route du Stade 17550 Dolus-d’Oléron        NaN        NaN
35       avenue des Rives du Lac 70000 Vesoul-Vaivre  47.629332   6.124113
36              76 Promenade de la Digue 26110 Nyons        NaN        NaN
37                    le Pont Rouge 85560 Le Bernard  46.455477   1.417809
38       D981 route d’Alès 30700 Serviers-et-Labaume  44.037562   4.326302
39              Chemin des dunes 34300 Le Cap d’Agde  43.282884   3.473722
40                        Les Ondines 46200 Souillac        NaN        NaN
41              500 route des Envignes 74160 Neydens  46.122615   6.095456
42               800 Allée de Beaulieu 84170 Monteux  44.021004   4.967534
43                Chemin de Zucculana 20620 Biguglia  42.628914   9.444885
44    Avenue René Monory 86360 Chasseneuil-du-Poitou  46.663320   0.361748
45                  4-6 rue Louis Armand 75015 Paris  48.833049   2.277545
46        De Pannelaan 68 B-8660 De Panne (Belgique)  51.081758   2.601974

In [10]:
df

,nom,url,adresse,latitude,longitude
0,Accueil,https://www.parcs-aquatiques.com/,NaN,NaN,NaN
1,Promos,https://www.parcs-aquatiques.com/promo-billets...,NaN,NaN,NaN
2,Carte France,https://www.parcs-aquatiques.com/parcs-aquatiq...,NaN,NaN,NaN
3,Aqualand,https://www.parcs-aquatiques.com/promo-billet-...,NaN,NaN,NaN
4,Agen,https://www.parcs-aquatiques.com/aqualand-agen/,Château de Caudouin 47310 Roquefort,44.186173,0.579221
5,Bassin d’Arcachon,https://www.parcs-aquatiques.com/aqualand-bass...,route des lacs 33470 Gujan-Mestras,NaN,NaN
6,Cap d’Agde,https://www.parcs-aquatiques.com/aqualand-capd...,2 avenue des Iles d’Amérique 34300 Le Cap d’Agde,43.280843,3.494517
7,Fréjus,https://www.parcs-aquatiques.com/aqualand-frejus/,Quartier le Capou D559 83600 Fréjus,43.419434,6.728501
8,Port Leucate,https://www.parcs-aquatiques.com/aqualand-port...,avenue du Roussillon 11370 Port Leucate,42.842203,3.042208
9,Saint Cyprien,https://www.parcs-aquatiques.com/aqualand-sain...,avenue des Champs de Neptune 66750 Saint Cyprien,42.601210,3.032193
10,Saint Cyr sur Mer,https://www.parcs-aquatiques.com/aqualand-sain...,ZAC des Pradeaux 83270 Saint-Cyr-sur-Mer,43.184257,5.692833
11,Sainte Maxime,https://www.parcs-aquatiques.com/aqualand-sain...,Avenue Gaston Rebuffat 83120 Sainte Maxime,43.327553,6.619147
12,Aquasplash,https://www.parcs-aquatiques.com/aquasplash-an...,306 avenue Mozart 06600 Antibes,43.614914,7.120413
13,Aquascope,https://www.parcs-aquatiques.com/aquascope-fut...,Avenue René Monory 86360 Chasseneuil-du-Poitou,46.663320,0.361748
14,Aquaboulevard,https://www.parcs-aquatiques.com/aquaboulevard...,4-6 rue Louis Armand 75015 Paris,48.833049,2.277545
15,Aqua Béarnà Oloron Sainte Marie,https://www.parcs-aquatiques.com/aqua-bearn-ol...,Le Faget de Goès 64400 Goès,NaN,NaN
16,Aquaboulevardà Paris,https://www.parcs-aquatiques.com/aquaboulevard...,4-6 rue Louis Armand 75015 Paris,48.833049,2.277545
17,Aqua’Fun Park – Cobac Parcà Lanhélin,https://www.parcs-aquatiques.com/aquafun-park-...,route D75 35620 Lanhélin,NaN,NaN
18,Aquajetà Narbonne Plage,https://www.parcs-aquatiques.com/aquajet-narbo...,route de Gruissan 11100 Narbonne Plage,43.147748,3.153190
19,Aqualand Agen– Walygator Sud Ouest,https://www.parcs-aquatiques.com/aqualand-agen/,Château de Caudouin 47310 Roquefort,44.186173,0.579221
20,Aqualand Bassin d’Arcachon,https://www.parcs-aquatiques.com/aqualand-bass...,route des lacs 33470 Gujan-Mestras,NaN,NaN
21,Aqualand Fréjus,https://www.parcs-aquatiques.com/aqualand-frejus/,Quartier le Capou D559 83600 Fréjus,43.419434,6.728501
22,Aqualand Le Cap d’Agde,https://www.parcs-aquatiques.com/aqualand-capd...,2 avenue des Iles d’Amérique 34300 Le Cap d’Agde,43.280843,3.494517
23,Aqualand Port Leucate,https://www.parcs-aquatiques.com/aqualand-port...,avenue du Roussillon 11370 Port Leucate,42.842203,3.042208
24,Aqualand Saint Cyprien,https://www.parcs-aquatiques.com/aqualand-sain...,avenue des Champs de Neptune 66750 Saint Cyprien,42.601210,3.032193
25,Aqualand Saint Cyr sur Mer,https://www.parcs-aquatiques.com/aqualand-sain...,ZAC des Pradeaux 83270 Saint-Cyr-sur-Mer,43.184257,5.692833
26,Aqualand Sainte Maxime,https://www.parcs-aquatiques.com/aqualand-sain...,Avenue Gaston Rebuffat 83120 Sainte Maxime,43.327553,6.619147
27,Aquaparc Isisà Dole,https://www.parcs-aquatiques.com/aquaparc-isis...,Allée des Prés Buffard 39100 Dole,47.073275,5.486750
28,Aquascope Futuroscope,https://www.parcs-aquatiques.com/aquascope-fut...,Avenue René Monory 86360 Chasseneuil-du-Poitou,46.663320,0.361748
29,Aquasplashà Antibes,https://www.parcs-aquatiques.com/aquasplash-an...,306 avenue Mozart 06600 Antibes,43.614914,7.120413
30,Aquatic Landesà Labenne-Océan,https://www.parcs-aquatiques.com/aquatic-lande...,route de la Plage 40530 Labenne-Océan,NaN,NaN
31,Atlantic Parkà Seignosse Océan,https://www.parcs-aquatiques.com/atlantic-park...,2 avenue de la Grande Plage 40510 Seignosse,NaN,NaN
32,Atlantic Tobogganà Saint-Hilaire-de-Riez,https://www.parcs-aquatiques.com/atlantic-tobo...,42 Avenue des Becs 85270 Saint-Hilaire-de-Riez,46.764210,2.031610
33,Espace Grand Bleuà La Grande Motte,https://www.parcs-aquatiques.com/espace-grand-...,195 rue Saint-Louis 34280 La Grande Motte,43.562553,4.098635
34,Iléosur l’île d’Oléron,https://www.parcs-aquatiques.com/ileo-dolus-ol...,"Iléo, route du Stade 17550 Dolus-d’Oléron",NaN,NaN
35,Ludolacà Vesoul,https://www.parcs-aquatiques.com/ludolac-vesoul/,avenue des Rives du Lac 70000 Vesoul-Vaivre,47.629332,6.124113
36,Nyonsoleïadoà Nyons,https://www.parcs-aquatiques.com/nyonsoleiado/,76 Promenade de la Digue 26110 Nyons,NaN,NaN
37,O’Gliss Parken Vendée,https://www.parcs-aquatiques.com/ogliss-park-v...,le Pont Rouge 85560 Le Bernard,46.455477,1.417809
38,Parc de la Bouscarasseà Serviers-et-Labaume,https://www.parcs-aquatiques.com/parc-bouscara...,D981 route d’Alès 30700 Serviers-et-Labaume,44.037562,4.326302
39,Pirates WorldCap d’Agde,https://www.parcs-aquatiques.com/baie-des-pira...,Chemin des dunes 34300 Le Cap d’Agde,43.282884,3.473722
40,Quercylandà Souillac,https://www.parcs-aquatiques.com/quercyland-so...,Les Ondines 46200 Souillac,NaN,NaN
41,Vitam à Neydens,https://www.parcs-aquatiques.com/vitam/,500 route des Envignes 74160 Neydens,46.122615,6.095456
42,Wave Islandà Monteux,https://www.parcs-aquatiques.com/splashworld-p...,800 Allée de Beaulieu 84170 Monteux,44.021004,4.967534
43,Western Parkà Biguglia,https://www.parcs-aquatiques.com/western-splas...,Chemin de Zucculana 20620 Biguglia,42.628914,9.444885
44,• Aquascope Futuroscope,https://www.parcs-aquatiques.com/aquascope-fut...,Avenue René Monory 86360 Chasseneuil-du-Poitou,46.663320,0.361748
45,• Aquaboulevard Paris,https://www.parcs-aquatiques.com/aquaboulevard...,4-6 rue Louis Armand 75015 Paris,48.833049,2.277545
46,• Plopsaqua,https://www.parcs-aquatiques.com/plopsaqua-lap...,De Pannelaan 68 B-8660 De Panne (Belgique),51.081758,2.601974

In [11]:
df = df.dropna(subset="adresse")

In [12]:
df

,nom,url,adresse,latitude,longitude
4,Agen,https://www.parcs-aquatiques.com/aqualand-agen/,Château de Caudouin 47310 Roquefort,44.186173,0.579221
5,Bassin d’Arcachon,https://www.parcs-aquatiques.com/aqualand-bass...,route des lacs 33470 Gujan-Mestras,NaN,NaN
6,Cap d’Agde,https://www.parcs-aquatiques.com/aqualand-capd...,2 avenue des Iles d’Amérique 34300 Le Cap d’Agde,43.280843,3.494517
7,Fréjus,https://www.parcs-aquatiques.com/aqualand-frejus/,Quartier le Capou D559 83600 Fréjus,43.419434,6.728501
8,Port Leucate,https://www.parcs-aquatiques.com/aqualand-port...,avenue du Roussillon 11370 Port Leucate,42.842203,3.042208
9,Saint Cyprien,https://www.parcs-aquatiques.com/aqualand-sain...,avenue des Champs de Neptune 66750 Saint Cyprien,42.601210,3.032193
10,Saint Cyr sur Mer,https://www.parcs-aquatiques.com/aqualand-sain...,ZAC des Pradeaux 83270 Saint-Cyr-sur-Mer,43.184257,5.692833
11,Sainte Maxime,https://www.parcs-aquatiques.com/aqualand-sain...,Avenue Gaston Rebuffat 83120 Sainte Maxime,43.327553,6.619147
12,Aquasplash,https://www.parcs-aquatiques.com/aquasplash-an...,306 avenue Mozart 06600 Antibes,43.614914,7.120413
13,Aquascope,https://www.parcs-aquatiques.com/aquascope-fut...,Avenue René Monory 86360 Chasseneuil-du-Poitou,46.663320,0.361748
14,Aquaboulevard,https://www.parcs-aquatiques.com/aquaboulevard...,4-6 rue Louis Armand 75015 Paris,48.833049,2.277545
15,Aqua Béarnà Oloron Sainte Marie,https://www.parcs-aquatiques.com/aqua-bearn-ol...,Le Faget de Goès 64400 Goès,NaN,NaN
16,Aquaboulevardà Paris,https://www.parcs-aquatiques.com/aquaboulevard...,4-6 rue Louis Armand 75015 Paris,48.833049,2.277545
17,Aqua’Fun Park – Cobac Parcà Lanhélin,https://www.parcs-aquatiques.com/aquafun-park-...,route D75 35620 Lanhélin,NaN,NaN
18,Aquajetà Narbonne Plage,https://www.parcs-aquatiques.com/aquajet-narbo...,route de Gruissan 11100 Narbonne Plage,43.147748,3.153190
19,Aqualand Agen– Walygator Sud Ouest,https://www.parcs-aquatiques.com/aqualand-agen/,Château de Caudouin 47310 Roquefort,44.186173,0.579221
20,Aqualand Bassin d’Arcachon,https://www.parcs-aquatiques.com/aqualand-bass...,route des lacs 33470 Gujan-Mestras,NaN,NaN
21,Aqualand Fréjus,https://www.parcs-aquatiques.com/aqualand-frejus/,Quartier le Capou D559 83600 Fréjus,43.419434,6.728501
22,Aqualand Le Cap d’Agde,https://www.parcs-aquatiques.com/aqualand-capd...,2 avenue des Iles d’Amérique 34300 Le Cap d’Agde,43.280843,3.494517
23,Aqualand Port Leucate,https://www.parcs-aquatiques.com/aqualand-port...,avenue du Roussillon 11370 Port Leucate,42.842203,3.042208
24,Aqualand Saint Cyprien,https://www.parcs-aquatiques.com/aqualand-sain...,avenue des Champs de Neptune 66750 Saint Cyprien,42.601210,3.032193
25,Aqualand Saint Cyr sur Mer,https://www.parcs-aquatiques.com/aqualand-sain...,ZAC des Pradeaux 83270 Saint-Cyr-sur-Mer,43.184257,5.692833
26,Aqualand Sainte Maxime,https://www.parcs-aquatiques.com/aqualand-sain...,Avenue Gaston Rebuffat 83120 Sainte Maxime,43.327553,6.619147
27,Aquaparc Isisà Dole,https://www.parcs-aquatiques.com/aquaparc-isis...,Allée des Prés Buffard 39100 Dole,47.073275,5.486750
28,Aquascope Futuroscope,https://www.parcs-aquatiques.com/aquascope-fut...,Avenue René Monory 86360 Chasseneuil-du-Poitou,46.663320,0.361748
29,Aquasplashà Antibes,https://www.parcs-aquatiques.com/aquasplash-an...,306 avenue Mozart 06600 Antibes,43.614914,7.120413
30,Aquatic Landesà Labenne-Océan,https://www.parcs-aquatiques.com/aquatic-lande...,route de la Plage 40530 Labenne-Océan,NaN,NaN
31,Atlantic Parkà Seignosse Océan,https://www.parcs-aquatiques.com/atlantic-park...,2 avenue de la Grande Plage 40510 Seignosse,NaN,NaN
32,Atlantic Tobogganà Saint-Hilaire-de-Riez,https://www.parcs-aquatiques.com/atlantic-tobo...,42 Avenue des Becs 85270 Saint-Hilaire-de-Riez,46.764210,2.031610
33,Espace Grand Bleuà La Grande Motte,https://www.parcs-aquatiques.com/espace-grand-...,195 rue Saint-Louis 34280 La Grande Motte,43.562553,4.098635
34,Iléosur l’île d’Oléron,https://www.parcs-aquatiques.com/ileo-dolus-ol...,"Iléo, route du Stade 17550 Dolus-d’Oléron",NaN,NaN
35,Ludolacà Vesoul,https://www.parcs-aquatiques.com/ludolac-vesoul/,avenue des Rives du Lac 70000 Vesoul-Vaivre,47.629332,6.124113
36,Nyonsoleïadoà Nyons,https://www.parcs-aquatiques.com/nyonsoleiado/,76 Promenade de la Digue 26110 Nyons,NaN,NaN
37,O’Gliss Parken Vendée,https://www.parcs-aquatiques.com/ogliss-park-v...,le Pont Rouge 85560 Le Bernard,46.455477,1.417809
38,Parc de la Bouscarasseà Serviers-et-Labaume,https://www.parcs-aquatiques.com/parc-bouscara...,D981 route d’Alès 30700 Serviers-et-Labaume,44.037562,4.326302
39,Pirates WorldCap d’Agde,https://www.parcs-aquatiques.com/baie-des-pira...,Chemin des dunes 34300 Le Cap d’Agde,43.282884,3.473722
40,Quercylandà Souillac,https://www.parcs-aquatiques.com/quercyland-so...,Les Ondines 46200 Souillac,NaN,NaN
41,Vitam à Neydens,https://www.parcs-aquatiques.com/vitam/,500 route des Envignes 74160 Neydens,46.122615,6.095456
42,Wave Islandà Monteux,https://www.parcs-aquatiques.com/splashworld-p...,800 Allée de Beaulieu 84170 Monteux,44.021004,4.967534
43,Western Parkà Biguglia,https://www.parcs-aquatiques.com/western-splas...,Chemin de Zucculana 20620 Biguglia,42.628914,9.444885
44,• Aquascope Futuroscope,https://www.parcs-aquatiques.com/aquascope-fut...,Avenue René Monory 86360 Chasseneuil-du-Poitou,46.663320,0.361748
45,• Aquaboulevard Paris,https://www.parcs-aquatiques.com/aquaboulevard...,4-6 rue Louis Armand 75015 Paris,48.833049,2.277545
46,• Plopsaqua,https://www.parcs-aquatiques.com/plopsaqua-lap...,De Pannelaan 68 B-8660 De Panne (Belgique),51.081758,2.601974

In [13]:
df.to_csv("parc_aquatique.csv")