In [55]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import re
import json
from tqdm import tqdm

In [56]:
df1 = pd.read_csv("C:/Users/jadeb/projet 3/MoveinLoc/projet 3 df/df_33.csv")
df2 = pd.read_csv("C:/Users/jadeb/projet 3/MoveinLoc/projet 3 df/df_56-57.csv")
df3 = pd.read_csv("C:/Users/jadeb/projet 3/MoveinLoc/projet 3 df/df_75.csv")
df4 = pd.read_csv("C:/Users/jadeb/projet 3/MoveinLoc/projet 3 df/df_77.csv")
df5 = pd.read_csv("C:/Users/jadeb/projet 3/MoveinLoc/projet 3 df/df_78.csv")
df6 = pd.read_csv("C:/Users/jadeb/projet 3/MoveinLoc/projet 3 df/df_91.csv")
df7 = pd.read_csv("C:/Users/jadeb/projet 3/MoveinLoc/projet 3 df/df_92.csv")
df8 = pd.read_csv("C:/Users/jadeb/projet 3/MoveinLoc/projet 3 df/df_93.csv")
df9 = pd.read_csv("C:/Users/jadeb/projet 3/MoveinLoc/projet 3 df/df_94.csv")
df10 = pd.read_csv("C:/Users/jadeb/projet 3/MoveinLoc/projet 3 df/df_95.csv")
df11 = pd.read_csv("C:/Users/jadeb/projet 3/MoveinLoc/projet 3 df/df_0157.csv")
df12 = pd.read_csv("C:/Users/jadeb/projet 3/MoveinLoc/projet 3 df/df_5890.csv")

In [57]:
df1 = pd.concat([df1,df2])

In [58]:
df1 = pd.concat([df1,df3])

In [59]:
df1 = pd.concat([df1,df4])

In [60]:
df1 = pd.concat([df1,df5])

In [61]:
df1 = pd.concat([df1,df6])

In [62]:
df1 = pd.concat([df1,df7])

In [63]:
df1 = pd.concat([df1,df8])

In [64]:
df1 = pd.concat([df1,df9])

In [65]:
df1 = pd.concat([df1,df10])

In [66]:
df1 = pd.concat([df1,df11])

In [67]:
df = pd.concat([df1,df12])

In [68]:
df.head()

,Unnamed: 0,theme,nom_event,adresse,ville,cp,dep,date_d,date_f,site_web
0,0,Marchés,MARCHÉ MARDI,Place Weiss 33740 ARES,ARES,33740.0,33,23 June 2026,NaN,NaN
1,1,Marchés,MARCHÉ MUNICIPAL,halle du marché et sur l’avenue du Général de ...,AUDENGE,33980.0,33,23 June 2026,NaN,NaN
2,2,Fêtes locales,Fêtes de la Saint Jean à Bazas,Place de la Cathédrale 33430 BAZAS,BAZAS,33430.0,33,23 June 2026,NaN,NaN
3,3,Marchés aux puces,Les Puces Saint Michel du mardi,Place saint Michel,BORDEAUX,33800.0,33,23 June 2026,NaN,NaN
4,4,Lotos Quines et Rifles,Méga Loto du mardi,17 rue Edgard faure ESPACE DS BORDEAUX LAC Bor...,BORDEAUX,33800.0,33,23 June 2026,NaN,NaN

In [69]:
df.info()

<class 'pandas.DataFrame'>
Index: 40167 entries, 0 to 12460
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  40167 non-null  int64
 1   theme       40167 non-null  str
 2   nom_event   40166 non-null  str
 3   adresse     19881 non-null  str
 4   ville       40167 non-null  str
 5   cp          40165 non-null  float64
 6   dep         40167 non-null  object
 7   date_d      40165 non-null  str
 8   date_f      665 non-null    object
 9   site_web    0 non-null      float64
dtypes: float64(2), int64(1), object(2), str(5)
memory usage: 6.2+ MB

In [70]:
df["cp"] = df["cp"].fillna(0)

In [71]:
df["cp"] = df["cp"].astype(int)

In [72]:
df["cp"] = df["cp"].astype(str)

In [73]:
df["adresse"] = df["adresse"].str.replace(r"\s+\d{5}.*$", "", regex=True)

In [74]:
df.head()

,Unnamed: 0,theme,nom_event,adresse,ville,cp,dep,date_d,date_f,site_web
0,0,Marchés,MARCHÉ MARDI,Place Weiss,ARES,33740,33,23 June 2026,NaN,NaN
1,1,Marchés,MARCHÉ MUNICIPAL,halle du marché et sur l’avenue du Général de ...,AUDENGE,33980,33,23 June 2026,NaN,NaN
2,2,Fêtes locales,Fêtes de la Saint Jean à Bazas,Place de la Cathédrale,BAZAS,33430,33,23 June 2026,NaN,NaN
3,3,Marchés aux puces,Les Puces Saint Michel du mardi,Place saint Michel,BORDEAUX,33800,33,23 June 2026,NaN,NaN
4,4,Lotos Quines et Rifles,Méga Loto du mardi,17 rue Edgard faure ESPACE DS BORDEAUX LAC Bor...,BORDEAUX,33800,33,23 June 2026,NaN,NaN

In [75]:
df["adresse_complete"] = df["adresse"] + " " + df["cp"] + " " + df["ville"]

In [76]:
df.info()

<class 'pandas.DataFrame'>
Index: 40167 entries, 0 to 12460
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        40167 non-null  int64
 1   theme             40167 non-null  str
 2   nom_event         40166 non-null  str
 3   adresse           19881 non-null  str
 4   ville             40167 non-null  str
 5   cp                40167 non-null  str
 6   dep               40167 non-null  object
 7   date_d            40165 non-null  str
 8   date_f            665 non-null    object
 9   site_web          0 non-null      float64
 10  adresse_complete  19881 non-null  str
dtypes: float64(1), int64(1), object(2), str(7)
memory usage: 7.4+ MB

In [77]:
mask = df["adresse"].isna() | (df["adresse"].str.strip() == "")

df["adresse_complete"] = (
    df["adresse"].fillna("").str.strip()
    + " "
    + df["cp"].astype(str)
    + " "
    + df["ville"].fillna("")
).str.strip()

In [78]:
df.head()

,Unnamed: 0,theme,nom_event,adresse,ville,cp,dep,date_d,date_f,site_web,adresse_complete
0,0,Marchés,MARCHÉ MARDI,Place Weiss,ARES,33740,33,23 June 2026,NaN,NaN,Place Weiss 33740 ARES
1,1,Marchés,MARCHÉ MUNICIPAL,halle du marché et sur l’avenue du Général de ...,AUDENGE,33980,33,23 June 2026,NaN,NaN,halle du marché et sur l’avenue du Général de ...
2,2,Fêtes locales,Fêtes de la Saint Jean à Bazas,Place de la Cathédrale,BAZAS,33430,33,23 June 2026,NaN,NaN,Place de la Cathédrale 33430 BAZAS
3,3,Marchés aux puces,Les Puces Saint Michel du mardi,Place saint Michel,BORDEAUX,33800,33,23 June 2026,NaN,NaN,Place saint Michel 33800 BORDEAUX
4,4,Lotos Quines et Rifles,Méga Loto du mardi,17 rue Edgard faure ESPACE DS BORDEAUX LAC Bor...,BORDEAUX,33800,33,23 June 2026,NaN,NaN,17 rue Edgard faure ESPACE DS BORDEAUX LAC Bor...

In [79]:
df.info()

<class 'pandas.DataFrame'>
Index: 40167 entries, 0 to 12460
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        40167 non-null  int64
 1   theme             40167 non-null  str
 2   nom_event         40166 non-null  str
 3   adresse           19881 non-null  str
 4   ville             40167 non-null  str
 5   cp                40167 non-null  str
 6   dep               40167 non-null  object
 7   date_d            40165 non-null  str
 8   date_f            665 non-null    object
 9   site_web          0 non-null      float64
 10  adresse_complete  40167 non-null  str
dtypes: float64(1), int64(1), object(2), str(7)
memory usage: 7.7+ MB

In [81]:
df.to_csv("dfjade.csv")

In [30]:
df["date_d"] = pd.to_datetime(df["date_d"], format="%d %B %Y").dt.date

ValueError: time data "vide grenier" doesn't match format "%d %B %Y". You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [31]:
df["date_d"].unique()

<ArrowStringArray>
[                                                             '23 June 2026',
                                                              '24 June 2026',
                                                              '25 June 2026',
                                                              '26 June 2026',
                                                              '27 June 2026',
                                                              '28 June 2026',
                                                              '29 June 2026',
                                                              '30 June 2026',
                                                              '01 July 2026',
                                                              '02 July 2026',
 ...
                                                              '11 June 2028',
                                        'Réderie et exposition de tracteurs',
                                                         '25 September 2027',
                                                          '18 November 2028',
                                              'Où et quand nous retrouver ?',
                                                         '05 September 2027',
                                                          '14 December 2027',
                                                         '21 September 2027',
                                                           '09 January 2028',
 'Foire de Padoux : Une tradition agricole et conviviale au cœur des Vosges']
Length: 612, dtype: str

In [42]:
from datetime import date
df['date_d'] = pd.to_datetime(df['date_d'], format='%d %B %Y', errors='coerce').dt.date
start_date = date.today()

In [47]:
df['date_d'].isna().sum()

np.int64(32)

In [48]:
df[df['date_d'].isna()]

,Unnamed: 0,theme,nom_event,adresse,ville,cp,dep,date_d,date_f,site_web,adresse_complete
973,973,Vide-greniers,vide greniers,"Salle des fêtes, 17 grand rue,",ALBESTROFF,57670,57,NaT,NaN,NaN,"Salle des fêtes, 17 grand rue, 57670 ALBESTROFF"
173,173,Fêtes,Feu d'artifice le 13 juillet à Montévrain,Avenue François Mitterand,MONTEVRAIN,77144,77,NaT,NaN,NaN,Avenue François Mitterand 77144 MONTEVRAIN
169,169,Brocantes,BROCANTE DE L’ABBAYE,3 impasse de l'Abbaye,SAINT-MAUR-DES-FOSSES,94210,94,NaT,NaN,NaN,3 impasse de l'Abbaye 94210 SAINT-MAUR-DES-FOSSES
171,171,Brocantes,Foire à la Brocante de Sucy-en-brie,Centre Ville Rue Maurice Berteaux,SUCY-EN-BRIE,94880,94,NaT,NaN,NaN,Centre Ville Rue Maurice Berteaux 94880 SUCY-E...
505,505,Fêtes médiévales,La Fête de la sorcière,"Château de Coucy Rue du Château,",COUCY-LE-CHATEAU-AUFFRIQUE,2380,02,NaT,NaN,NaN,"Château de Coucy Rue du Château, 2380 COUCY-LE..."
1050,1050,Fêtes locales,Fête de la transhumance,Place Marcel Sauvaire,CASTELLANE,4120,04,NaT,NaN,NaN,Place Marcel Sauvaire 4120 CASTELLANE
2003,2003,Foires,FOIRE DE LA SAINT-ANTOINE,"boulevards Pasteur, Gambetta et Vernon Aubenas -",AUBENAS,7200,07,NaT,NaN,NaN,"boulevards Pasteur, Gambetta et Vernon Aubenas..."
2004,2004,"Randonnées, Trail ou Running",RBMA... le retour (raid blanc de la Montagne A...,Station de la Croix de Bauzon,BORNE,7590,07,NaT,NaN,NaN,Station de la Croix de Bauzon 7590 BORNE
2947,2947,Stages Ateliers,stage de poterie : La vie en Relief,1285 Chemin du moulin du Fort,AIX-EN-PROVENCE,13540,13,NaT,NaN,NaN,1285 Chemin du moulin du Fort 13540 AIX-EN-PRO...
3698,3698,Vide-greniers,Cadolive Vide grenier annuel 1ER mai,village,CADOLIVE,13950,13,NaT,NaN,NaN,village 13950 CADOLIVE
3719,3719,Sorties Moto,La bénédiction des motards,Bonne Mère,MARSEILLE,13016,13,NaT,NaN,NaN,Bonne Mère 13016 MARSEILLE
4477,4477,Concerts,DUO 6/4 ODEON,Auditorium du conservatoire 5 esplanade Franço...,HEROUVILLE-SAINT-CLAIR,14200,14,NaT,NaN,NaN,Auditorium du conservatoire 5 esplanade Franço...
4478,4478,Concerts,DUO 6/4 ODEON,Auditorium du conservatoire 5 esplanade Franço...,HEROUVILLE-SAINT-CLAIR,14200,14,NaT,NaN,NaN,Auditorium du conservatoire 5 esplanade Franço...
7596,7596,Fêtes locales,Fête de la Rhubarbe,Musée,VALENTIGNEY,25700,25,NaT,NaN,NaN,Musée 25700 VALENTIGNEY
7733,7733,Fêtes locales,Fête Communale d’Ambonil,AMBONIL,AMBONIL,26800,26,NaT,NaN,NaN,AMBONIL 26800 AMBONIL
9935,9935,"Randonnées, Trail ou Running",RAID MULTISPORTS VERNET,SALLE DES FETES,VERNET,31810,31,NaT,NaN,NaN,SALLE DES FETES 31810 VERNET
10786,10786,Festivals,Festival de Bandas à Condom,Condom village,CONDOM,0,32,NaT,NaN,NaN,Condom village 0 CONDOM
11703,11703,Spectacles,NaN,NaN,RENNES -,0,35,NaT,NaN,NaN,0 RENNES -
13309,13309,Vide-greniers,Villeloin-Coulangé - Brocante vide-grenier,Dans les rues du village,VILLELOIN-COULANGE,37460,37,NaT,NaN,NaN,Dans les rues du village 37460 VILLELOIN-COULANGE
14895,14895,Evènements VTT,La Troglobike - VTT &#128690;,Centre ville,MONTOIRE-SUR-LE-LOIR,41800,41,NaT,NaN,NaN,Centre ville 41800 MONTOIRE-SUR-LE-LOIR
14915,14915,Messes,Messe du jour de Noel,Huisseau-sur-Cosson,HUISSEAU-SUR-COSSON,41350,41,NaT,NaN,NaN,Huisseau-sur-Cosson 41350 HUISSEAU-SUR-COSSON
14925,14925,Bourses,"Bourse d'Echange auto, moto, vélo, tracteur",place Lucien Guerrier,NOYERS-SUR-CHER,41140,41,NaT,NaN,NaN,place Lucien Guerrier 41140 NOYERS-SUR-CHER
1773,1773,Foires,&#127792; Foire aux marrons d’Attichy,Village,ATTICHY,60350,60,NaT,NaN,NaN,Village 60350 ATTICHY
2448,2448,Fêtes locales,Fête des 2 Caps,62179 AUDINGHEN,AUDINGHEN,62179,62,NaT,NaN,NaN,62179 AUDINGHEN 62179 AUDINGHEN
2893,2893,Marchés de Producteurs,marché de producteurs,Place de l’Hôtel de ville Pont-du-Château -,PONT-DU-CHATEAU,63430,63,NaT,NaN,NaN,Place de l’Hôtel de ville Pont-du-Château - 63...
2966,2966,Vide-greniers,Grand Vide-Greniers Annuel de Veyre-Monton (63),complexe sportif,VEYRE-MONTON,63960,63,NaT,NaN,NaN,complexe sportif 63960 VEYRE-MONTON
4269,4269,Brocantes,marché aux puces brocantes,ROUTE DE THAL ET VOIE ROMAINE Mackwiller,MACKWILLER,67430,67,NaT,NaN,NaN,ROUTE DE THAL ET VOIE ROMAINE Mackwiller 67430...
6396,6396,Fêtes locales,Grande Fête Chasse Campagne,Le château,BRESSE-SUR-GROSNE,71460,71,NaT,NaN,NaN,Le château 71460 BRESSE-SUR-GROSNE
8561,8561,Spectacles,Ils Exagerent,"Théâtre à l'Ouest 26, quai Gaston Boulet ROUEN",ROUEN,76100,76,NaT,NaN,NaN,"Théâtre à l'Ouest 26, quai Gaston Boulet ROUEN..."
9105,9105,Vide-greniers,Réderie et exposition de tracteurs,NaN,BOUZINCOURT -,80300,80,NaT,NaN,NaN,80300 BOUZINCOURT -
10607,10607,Brocantes,14 juillet vide greniers Sault,Route de St Trinit,SAULT,84390,84,NaT,NaN,NaN,Route de St Trinit 84390 SAULT
12136,12136,Foires,FOIRE AUX BÊTES D'EMBOUCHE,Place du village,PADOUX,88700,88,NaT,NaN,NaN,Place du village 88700 PADOUX

In [49]:
df.info()

<class 'pandas.DataFrame'>
Index: 40167 entries, 0 to 12460
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        40167 non-null  int64
 1   theme             40167 non-null  str
 2   nom_event         40166 non-null  str
 3   adresse           19881 non-null  str
 4   ville             40167 non-null  str
 5   cp                40167 non-null  str
 6   dep               40167 non-null  object
 7   date_d            40135 non-null  object
 8   date_f            665 non-null    object
 9   site_web          0 non-null      float64
 10  adresse_complete  40167 non-null  str
dtypes: float64(1), int64(1), object(3), str(6)
memory usage: 7.2+ MB

In [40]:
df.to_csv("dfjade.csv")

In [52]:
df["date_d"] = pd.to_datetime(df["date_d"], format="%d %B %Y", errors='coerce').dt.date

# Et pour filtrer (pas de .dt disponible, comparaison directe) :
df[df["date_d"] >= start_date]

,Unnamed: 0,theme,nom_event,adresse,ville,cp,dep,date_d,date_f,site_web,adresse_complete
131,131,Concerts,"Festes Baroques, concert 2",1 place Pierre Renaudel,BORDEAUX,33800,33,2026-06-29,NaN,NaN,1 place Pierre Renaudel 33800 BORDEAUX
132,132,Fêtes locales,Fêtes de Boutoc,Boutoc,PREIGNAC,33210,33,2026-06-29,NaN,NaN,Boutoc 33210 PREIGNAC
133,133,Classique et opera,Ludovico einaudi,NaN,BORDEAUX -,33800,33,2026-06-30,NaN,NaN,33800 BORDEAUX -
134,134,Coups de coeur,Don du sang,Pôle Simone Veil 26 rue Aurel Chazeau,SAINT-MEDARD-EN-JALLES,33160,33,2026-06-30,NaN,NaN,Pôle Simone Veil 26 rue Aurel Chazeau 33160 SA...
135,135,Concerts,"Festes Baroques, concert 3",Château Carbonnieux chemin Peyssardet,BORDEAUX,33800,33,2026-07-01,NaN,NaN,Château Carbonnieux chemin Peyssardet 33800 BO...
...,...,...,...,...,...,...,...,...,...,...,...
12456,12456,Humour et one (wo)man show,Laura calu,NaN,BELFORT -,90000,90,2027-06-05,NaN,NaN,90000 BELFORT -
12457,12457,Spectacles,LAURA CALU,NaN,BELFORT -,90000,90,2027-06-05,NaN,NaN,90000 BELFORT -
12458,12458,Vide-greniers,Vide-greniers et marché aux puces,AU STADE Route de Chaux,ROUGEGOUTTE,90200,90,2027-06-20,NaN,NaN,AU STADE Route de Chaux 90200 ROUGEGOUTTE
12459,12459,Humour et one (wo)man show,Arnaud tsamere,NaN,BELFORT -,90000,90,2027-11-26,NaN,NaN,90000 BELFORT -
12460,12460,Spectacles,ARNAUD TSAMERE,NaN,BELFORT -,90000,90,2027-11-26,NaN,NaN,90000 BELFORT -