In [3]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import re

In [ ]:
HEADERS = {"User-Agent": "Mozilla/5.0 Chrome/124.0"}

def get_zoo_links():
    r = requests.get("https://www.zoofrance.com/carte/", headers=HEADERS)
    soup = BeautifulSoup(r.text, "html.parser")
    zoos = {}
    for li in soup.select("ul li a[href*='zoofrance.com']"):
        name = li.get_text(strip=True)
        href = li["href"]
        if name and "/carte" not in href:
            zoos[name] = href
    return zoos

def extract_info(url):
    r = requests.get(url, headers=HEADERS, timeout=15)
    soup = BeautifulSoup(r.text, "html.parser")

    adresse = None
    lat, lon = None, None

    # Chercher les balises <strong> qui contiennent "Adresse"
    for strong in soup.find_all("strong"):
        if "Adresse" in strong.get_text():
            # Le texte de l'adresse est dans le noeud suivant (NavigableString)
            next_node = strong.next_sibling
            if next_node:
                adresse = str(next_node).strip().lstrip(": ").strip()
            break

    # Coordonnées GPS
    gps_match = re.search(r"latitude\s*([\d.]+)\s*\|\s*longitude\s*([\d.]+)", soup.get_text())
    if gps_match:
        lat = float(gps_match.group(1))
        lon = float(gps_match.group(2))

    return {"adresse": adresse, "latitude": lat, "longitude": lon}

zoos = get_zoo_links()
records = []
for name, url in zoos.items():
    print(f"→ {name}")
    info = extract_info(url)
    records.append({"nom": name, "url": url, **info})
    time.sleep(0.8)

df = pd.DataFrame(records)
df.to_csv("zoos_france2.csv", index=False, encoding="utf-8-sig")
print(df[["nom", "adresse", "latitude", "longitude"]])

→ Accueil
→ Classement
→ Promo Billets
→ Beauval
→ Tarifs 2026
→ Séjours Hôtels
→ Prévisions fréquentation
→ Paris
→ Le PAL
→ Thoiry
→ Amnéville
→ La Flèche
→ Nausicaa
→ Sigean
→ Peaugres
→ La Palmyre
→ Lumigny
→ Barben
→ Doué la Fontaine
→ Aquarium de Paris
→ Aquarium de Saint-Malo
→ Aquarium La Rochelle
→ Bioparc de Doué la Fontaine
→ Biotropica
→ La Ferme aux Crocodiles
→ La Vallée des Singes
→ Les Terres de Nataé
→ Lumigny Safari Réserve
→ Océanopolis
→ Parc animalier de Sainte-Croix
→ Parc animalier des Pyrénées
→ Parc de Branféré
→ Parc de Merlet
→ Parc des Oiseaux
→ Parc Zoologique de Paris
→ Parc Zoo du Reynou
→ Planète Sauvage
→ Planet Exotica
→ Réserve de Sigean
→ Safari de Peaugres
→ Seaquarium
→ Touroparc
→ Zoo African Safari
→ Zoo d’Amiens
→ Zoo d’Amnéville
→ Zoo de Cerza
→ Zoo de Champrépus
→ Zoo de Jurques
→ Zoo de la Barben
→ Zoo de la Boissière du Doré
→ Zoo de la Flèche
→ Zoo de La Palmyre
→ Zoo de Lille
→ Zoo de Lyon
→ Zoo de Montpellier
→ Zoo de Mulhouse
→ Zoo des Sables d’Olonne
→ Zoo de Thoiry
→ Zoo du Bassin d’Arcachon
→ Zoo du PAL
→ ZooParc de Beauval
                         nom  \
0                    Accueil
1                 Classement
2              Promo Billets
3                    Beauval
4                Tarifs 2026
..                       ...
56   Zoo des Sables d’Olonne
57             Zoo de Thoiry
58  Zoo du Bassin d’Arcachon
59                Zoo du PAL
60        ZooParc de Beauval

                                              adresse   latitude  longitude
0                                                 NaN        NaN        NaN
1                                                 NaN        NaN        NaN
2                                                 NaN        NaN        NaN
3         Avenue du Blanc 41110 Saint-Aignan-sur-Cher  47.247579   1.353391
4                                                 NaN        NaN        NaN
..                                                ...        ...        ...
56  route du Tour de France 85100 Les Sables d’Olonne        NaN        NaN
57          rue du Pavillon de Montreuil 78770 Thoiry  48.863400   1.797880
58             route de Cazaux 33260 La Teste de Buch        NaN        NaN
59  Saint-Pourçain-sur-Besbre CS 60001 03290 Dompi...        NaN        NaN
60        Avenue du Blanc 41110 Saint-Aignan-sur-Cher  47.247579   1.353391

[61 rows x 4 columns]

In [12]:
df_zoo = pd.read_csv("C:/Users/jadeb/projet 3/MoveinLoc/zoos_france2.csv")

In [14]:
df_zoo.head(15)

,nom,url,adresse,latitude,longitude
0,Accueil,https://www.zoofrance.com/,NaN,NaN,NaN
1,Classement,https://www.zoofrance.com/classement-zoos-france/,NaN,NaN,NaN
2,Promo Billets,https://www.zoofrance.com/zoo-beauval/promo-bi...,NaN,NaN,NaN
3,Beauval,https://www.zoofrance.com/zoo-beauval/,Avenue du Blanc 41110 Saint-Aignan-sur-Cher,47.247579,1.353391
4,Tarifs 2026,https://www.zoofrance.com/zoo-beauval/tarifs-b...,NaN,NaN,NaN
5,Séjours Hôtels,https://www.zoofrance.com/zoo-beauval/hotels/,Route de Beauval 41110 Saint-Aignan-sur-Cher,NaN,NaN
6,Prévisions fréquentation,https://www.zoofrance.com/zoo-beauval/previsio...,NaN,NaN,NaN
7,Paris,https://www.zoofrance.com/zoo-paris-vincennes/,route de la Ceinture du Lac Daumesnil 75012 Paris,48.833750,2.412730
8,Le PAL,https://www.zoofrance.com/zoo-le-pal/,Saint-Pourçain-sur-Besbre CS 60001 03290 Dompi...,NaN,NaN
9,Thoiry,https://www.zoofrance.com/zoo-thoiry/,rue du Pavillon de Montreuil 78770 Thoiry,48.863400,1.797880
10,Amnéville,https://www.zoofrance.com/zoo-amneville/,1 rue du Tigre 57360 Amnéville,49.245553,6.137827
11,La Flèche,https://www.zoofrance.com/zoo-la-fleche/,Le Tertre Rouge 72200 La Flèche,NaN,NaN
12,Nausicaa,https://www.zoofrance.com/nausicaa-boulogne-su...,Boulevard Sainte Beuve 62203 Boulogne-sur-Mer,50.730934,1.595746
13,Sigean,https://www.zoofrance.com/reserve-africaine-si...,19 Chemin Hameau du lac 11130 Sigean,43.062710,2.949801
14,Peaugres,https://www.zoofrance.com/safari-peaugres/,Safari de Peaugres 07340 Peaugres,45.269590,4.713520

In [15]:
df_zoo.info()

<class 'pandas.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   nom        61 non-null     str
 1   url        61 non-null     str
 2   adresse    56 non-null     str
 3   latitude   28 non-null     float64
 4   longitude  28 non-null     float64
dtypes: float64(2), str(3)
memory usage: 8.2 KB

In [16]:
df_zoo = df.dropna(subset="adresse")

In [17]:
df_zoo

,nom,url,adresse,latitude,longitude
3,Beauval,https://www.zoofrance.com/zoo-beauval/,Avenue du Blanc 41110 Saint-Aignan-sur-Cher,47.247579,1.353391
5,Séjours Hôtels,https://www.zoofrance.com/zoo-beauval/hotels/,Route de Beauval 41110 Saint-Aignan-sur-Cher,NaN,NaN
7,Paris,https://www.zoofrance.com/zoo-paris-vincennes/,route de la Ceinture du Lac Daumesnil 75012 Paris,48.833750,2.412730
8,Le PAL,https://www.zoofrance.com/zoo-le-pal/,Saint-Pourçain-sur-Besbre CS 60001 03290 Dompi...,NaN,NaN
9,Thoiry,https://www.zoofrance.com/zoo-thoiry/,rue du Pavillon de Montreuil 78770 Thoiry,48.863400,1.797880
10,Amnéville,https://www.zoofrance.com/zoo-amneville/,1 rue du Tigre 57360 Amnéville,49.245553,6.137827
11,La Flèche,https://www.zoofrance.com/zoo-la-fleche/,Le Tertre Rouge 72200 La Flèche,NaN,NaN
12,Nausicaa,https://www.zoofrance.com/nausicaa-boulogne-su...,Boulevard Sainte Beuve 62203 Boulogne-sur-Mer,50.730934,1.595746
13,Sigean,https://www.zoofrance.com/reserve-africaine-si...,19 Chemin Hameau du lac 11130 Sigean,43.062710,2.949801
14,Peaugres,https://www.zoofrance.com/safari-peaugres/,Safari de Peaugres 07340 Peaugres,45.269590,4.713520
15,La Palmyre,https://www.zoofrance.com/zoo-la-palmyre/,6 Avenue de Royan 17570 Les Mathes,NaN,NaN
16,Lumigny,https://www.zoofrance.com/parc-des-felins-nesles/,La Fortelle 77540 Lumigny-Nesles-Ormeaux,48.713934,2.959790
17,Barben,https://www.zoofrance.com/zoo-la-barben/,Route du Château 13330 La Barben,43.623500,5.205800
18,Doué la Fontaine,https://www.zoofrance.com/bioparc-doue-la-font...,103 rue de Cholet 49700 Doué-la-Fontaine,NaN,NaN
19,Aquarium de Paris,https://www.zoofrance.com/aquarium-de-paris/,5 Avenue Albert de Mun 75016 Paris,48.862236,2.290990
20,Aquarium de Saint-Malo,https://www.zoofrance.com/aquarium-saint-malo/,Avenue du Général Patton 35400 Saint-Malo,NaN,NaN
21,Aquarium La Rochelle,https://www.zoofrance.com/aquarium-la-rochelle/,Quai Louis Prunier 17000 La Rochelle,NaN,NaN
22,Bioparc de Doué la Fontaine,https://www.zoofrance.com/bioparc-doue-la-font...,103 rue de Cholet 49700 Doué-la-Fontaine,NaN,NaN
23,Biotropica,https://www.zoofrance.com/biotropica-val-de-re...,"CD110, Base de Loisirs – Butte de la Capoulade...",49.302550,1.206200
24,La Ferme aux Crocodiles,https://www.zoofrance.com/ferme-aux-crocodiles/,395 Allée de Beauplan 26700 Pierrelatte,44.356130,4.703480
25,La Vallée des Singes,https://www.zoofrance.com/vallee-des-singes/,Le Gureau 86700 Romagne,46.244744,0.291425
26,Les Terres de Nataé,https://www.zoofrance.com/zoo-pont-scorff/,LDT Kerruisseau 56620 Pont-Scorff,NaN,NaN
27,Lumigny Safari Réserve,https://www.zoofrance.com/parc-des-felins-nesles/,La Fortelle 77540 Lumigny-Nesles-Ormeaux,48.713934,2.959790
28,Océanopolis,https://www.zoofrance.com/oceanopolis-brest/,Port du Moulin blanc 29210 Brest,NaN,NaN
29,Parc animalier de Sainte-Croix,https://www.zoofrance.com/parc-sainte-croix/,route de Sainte-Croix 57810 Rhodes,48.768693,6.897268
30,Parc animalier des Pyrénées,https://www.zoofrance.com/parc-animalier-pyren...,60 bis avenue des Pyrénées 65400 Ayzac-Ost,NaN,NaN
31,Parc de Branféré,https://www.zoofrance.com/parc-branfere/,route de Branféré 56160 Le Guerno,NaN,NaN
32,Parc de Merlet,https://www.zoofrance.com/parc-de-merlet/,2495 Chemin de Merlet 74310 Les Houches,NaN,NaN
33,Parc des Oiseaux,https://www.zoofrance.com/parc-des-oiseaux-vil...,RD1083 01330 Villars-les-Dombes,45.992188,5.024234
34,Parc Zoologique de Paris,https://www.zoofrance.com/zoo-paris-vincennes/,route de la Ceinture du Lac Daumesnil 75012 Paris,48.833750,2.412730
35,Parc Zoo du Reynou,https://www.zoofrance.com/parc-zoo-reynou/,Domaine du Reynou 87110 Le Vigen,45.759177,1.299734
36,Planète Sauvage,https://www.zoofrance.com/planete-sauvage/,La Chevalerie 44710 Port Saint Père,NaN,NaN
37,Planet Exotica,https://www.zoofrance.com/planet-exotica/,5 avenue des Fleurs de la Paix 17204 Royan,NaN,NaN
38,Réserve de Sigean,https://www.zoofrance.com/reserve-africaine-si...,19 Chemin Hameau du lac 11130 Sigean,43.062710,2.949801
39,Safari de Peaugres,https://www.zoofrance.com/safari-peaugres/,Safari de Peaugres 07340 Peaugres,45.269590,4.713520
40,Seaquarium,https://www.zoofrance.com/seaquarium-grau-du-roi/,Avenue du Palais de la Mer 30240 Le Grau du Roi,NaN,NaN
41,Touroparc,https://www.zoofrance.com/touroparc/,400 rue du Parc 71570 Romanèche-Thorins,NaN,NaN
42,Zoo African Safari,https://www.zoofrance.com/african-safari/,41 rue des Landes 31830 Plaisance-du-Touch,43.560601,1.266232
43,Zoo d’Amiens,https://www.zoofrance.com/zoo-amiens/,Allée du zoo – Esplanade de la Hotoie 80000 Am...,49.898885,2.282392
44,Zoo d’Amnéville,https://www.zoofrance.com/zoo-amneville/,1 rue du Tigre 57360 Amnéville,49.245553,6.137827
45,Zoo de Cerza,https://www.zoofrance.com/cerza/,D143 14100 Hermival les Vaux,49.184173,0.309054
46,Zoo de Champrépus,https://www.zoofrance.com/zoo-champrepus/,493 rue Saint-Gaud 50800 Champrépus,NaN,NaN
47,Zoo de Jurques,https://www.zoofrance.com/zoo-de-jurques/,La Butte 14260 Dialan sur Chaîne,NaN,NaN
48,Zoo de la Barben,https://www.zoofrance.com/zoo-la-barben/,Route du Château 13330 La Barben,43.623500,5.205800
49,Zoo de la Boissière du Doré,https://www.zoofrance.com/zoo-boissiere-dore/,Lieu-dit La Châtaigneraie 44430 La Boissière-d...,NaN,NaN
50,Zoo de la Flèche,https://www.zoofrance.com/zoo-la-fleche/,Le Tertre Rouge 72200 La Flèche,NaN,NaN
51,Zoo de La Palmyre,https://www.zoofrance.com/zoo-la-palmyre/,6 Avenue de Royan 17570 Les Mathes,NaN,NaN
52,Zoo de Lille,https://www.zoofrance.com/zoo-lille/,Avenue Mathias Delobel 59000 Lille,NaN,NaN
53,Zoo de Lyon,https://www.zoofrance.com/zoo-lyon/,Allée de l’Orangerie 69006 Lyon,NaN,NaN
54,Zoo de Montpellier,https://www.zoofrance.com/zoo-montpellier/,50 Avenue Agropolis 34090 Montpellier,NaN,NaN
55,Zoo de Mulhouse,https://www.zoofrance.com/zoo-mulhouse/,111 avenue de la 1ère Division Blindée 68100 M...,47.731575,7.347215
56,Zoo des Sables d’Olonne,https://www.zoofrance.com/zoo-des-sables-dolonne/,route du Tour de France 85100 Les Sables d’Olonne,NaN,NaN
57,Zoo de Thoiry,https://www.zoofrance.com/zoo-thoiry/,rue du Pavillon de Montreuil 78770 Thoiry,48.863400,1.797880
58,Zoo du Bassin d’Arcachon,https://www.zoofrance.com/zoo-bassin-arcachon/,route de Cazaux 33260 La Teste de Buch,NaN,NaN
59,Zoo du PAL,https://www.zoofrance.com/zoo-le-pal/,Saint-Pourçain-sur-Besbre CS 60001 03290 Dompi...,NaN,NaN
60,ZooParc de Beauval,https://www.zoofrance.com/zoo-beauval/,Avenue du Blanc 41110 Saint-Aignan-sur-Cher,47.247579,1.353391

In [ ]:
df_zoo.to_csv("zoo_france.csv")

: